import { Activity, ArrowDown, ArrowUp, CheckCheck, ListTodo, UsersRound } from "lucide-react";

export function DashboardSummary({ openTasks, inProgressCount, completedCount }: { openTasks: number; inProgressCount: number; completedCount: number }) {
  return (
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Workspace summary">
      <article className="rounded-2xl border border-[#e9ebe5] bg-white p-5"><div className="flex items-start justify-between"><span className="text-[.72rem] font-semibold text-[#829087]">Open tasks</span><span className="grid size-9 place-items-center rounded-xl bg-[#e9f2ed] text-[#277365]"><ListTodo size={17} /></span></div><div className="mt-4 flex items-end justify-between"><span className="text-[1.8rem] font-semibold tracking-tight">{openTasks}</span><span className="inline-flex items-center gap-1 text-[.67rem] font-semibold text-[#39826d]"><ArrowDown size={13} /> 8% this week</span></div></article>
      <article className="rounded-2xl border border-[#e9ebe5] bg-white p-5"><div className="flex items-start justify-between"><span className="text-[.72rem] font-semibold text-[#829087]">In progress</span><span className="grid size-9 place-items-center rounded-xl bg-[#f8f0dc] text-[#ac872b]"><Activity size={17} /></span></div><div className="mt-4 flex items-end justify-between"><span className="text-[1.8rem] font-semibold tracking-tight">{inProgressCount}</span><span className="text-[.67rem] text-[#89948d]">Across 3 projects</span></div></article>
      <article className="rounded-2xl border border-[#e9ebe5] bg-white p-5"><div className="flex items-start justify-between"><span className="text-[.72rem] font-semibold text-[#829087]">Completed this week</span><span className="grid size-9 place-items-center rounded-xl bg-[#edf0f5] text-[#687994]"><CheckCheck size={17} /></span></div><div className="mt-4 flex items-end justify-between"><span className="text-[1.8rem] font-semibold tracking-tight">{completedCount}</span><span className="inline-flex items-center gap-1 text-[.67rem] font-semibold text-[#39826d]"><ArrowUp size={13} /> 12% this week</span></div></article>
      <article className="rounded-2xl border border-[#e9ebe5] bg-white p-5"><div className="flex items-start justify-between"><span className="text-[.72rem] font-semibold text-[#829087]">Team members</span><span className="grid size-9 place-items-center rounded-xl bg-[#f4e9e2] text-[#a36b4c]"><UsersRound size={17} /></span></div><div className="mt-4 flex items-end justify-between"><span className="text-[1.8rem] font-semibold tracking-tight">4</span><a className="text-[.67rem] font-semibold text-[#277365] hover:underline" href="#team">View team</a></div></article>
    </section>
  );
}